# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "maingit-branch--m-main-<BRANCH>-git-fetch-origin-git-branch--u-origin/<BRANCH>-<BRANCH>-git-remote-set-head-origin--a" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEPupNg1gu2wWnBIG0o4BC9gfWI9oFAmOA8FYACgkQo4BC9gfW

I9otDw//dJaJkhQKmPAeemNam63pPV1e4iw41//3pGxPx5MoVwlpenaalYUiNFBx

+mZYC7rMnnlZBg0nHw5RRyyIXW+XkwVyZCo8sGjOB/WoN7StncdqWpdY1PwZunLr

znoab+42taH33O+A3jAuOwI7p2E2pyhzfquo1lSSYMmf+KIyGENukw+CQwiArrfB

yswYlaWqR8gwnY8rvEsU9TgaDAyRU16scvSdlRzeerdGlUayWFalfsDCBV2CnlyN

YYtMvTuVpTKUfS9nXyJA5nlA45GF3ELm2vw69TufEAGtWbVKQW6ESRRWMv5f2a1B

qkeMfRbVOAqYtN3Ycp5ImrSorIOj2VRywuIn8pzbHKyVYrFzBf/DYXCVEHg/lwon

AoA/jZ6aGWwJdFKDmnJtes0MT11FdGCaD30HhOl85k+vql0u1bx1vwUXhBpmr5Vk

cso5wRbJy1jPchzSmpUKoeRCvMNijqR9awe4p1uIiYoJ0sWZA6ZxMwPVN3QQfGmU

poH58sewdQJzCMxM8y1qlp91IAzO6bxPckpaiI3Jx1ZBB3DWkkarzlzIcumcAc71

b0jOLHMg4GjGlbyECU1Bf9EpNsaVC162DaI9Ojoph1Izlgsx52VbSGXOolki8CXQ

nyleO20o6fp1qt/ArlOksiWrtgsk+SbcCwsayGC6ZzBFAbR+8+A=

=T4F/

-----END PGP SIGNATURE-----
